### ISSUE TITLE
Update to 62.0.3202.62

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#111]
please update for chromium 62

>i've all patches except "fix building without safebrowsing"

>i've just "sleep" it with prefs

**Comment by gcarq** [comment]
I'm compiling 62.0.3202.62 with updated patches from xsmile right now. So you can expect a release tomorrow or at the weekend.

@nyancat18 If you want to contribute with PRs please stick with small changesets and a clear description about what each commit does, otherwise it is not maintainable and therefore not merged.

**Comment by gcarq** [comment]
Released and uploaded to AUR
