### ISSUE TITLE
Add possibility to autoupdate extensions

### ISSUE THREAD

**Issue by Nycex** [gcarq/inox-patchset#146]
Inox disables the chrome store, but I want my extensions to be updated automatically, what they wont do, if i have to unpack them every time. Is there a possibility to this?

**Comment by Eloston** [comment]
There are external utilities to do this, but I'm not sure if they will do it in the background. In terms of a solution in the browser itself, there is a patch that currently disables some parts of the Chrome Web Store downloading mechanism since it depends on a hardcoded URL. But, since extensions include an update URL in the manifest file, it should be possible to modify the extension downloading code to use the update URL (which would make it possible to update extensions from any server).

**Comment by xsmile** [comment]
Also see the discussion at #7, especially the latest message. InspectorMustache wrote a nice tool to manually update extensions.
You could extend it with a systemd service and timer to periodically download new versions.

**Comment by Nycex** [comment]
Even if all directories exist, i get that message:
`
One or more paths provided in maninex.conf could not be found.
`
