### ISSUE TITLE
Disable missing key warning

### ISSUE THREAD

**Issue by dcousens** [gcarq/inox-patchset#2]
Hi @gcarq!

Great patch set,  going to be using this myself.
Could you explain the purpose behind https://github.com/gcarq/inox-patchset/blob/master/disable-missing-key-warning.patch ?

It wasn't explained in the README,  and I don't know enough about chromium to understand its purpose.

Thanks for any help,

**Comment by gcarq** [comment]
Hi,

Basically if you want to use Google Chrome APIs you need a Google API key,
this key is usually set on compile time and unique per distribution. 
See [Chromium PKGBUILD](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/chromium#n37)  on how it's applied or this [HOWTO](https://www.chromium.org/developers/how-tos/api-keys) for an in-depth API key explanation.

Since we don't want to use these APIs at all, the keys are not set (at least for inox package on AUR).
Now Chromium checks on each start if these keys are there, if not a warning is shown.
This is where this patch comes in and disables the warning dialog.

Thanks for pointing out, I will add it to the description.
