### ISSUE TITLE
Enhacement: Chromium 54

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#35]
Chromium 54 has arrived

please update inox

thanks

**Comment by nikolowry** [comment]
I've been using the inox patchset with AUR's (archlinux user repo) `chromium-dev` pkg. I'm on 56.0.2914.3 and can report all patches still work except the following:

- `disable-autofill-download-manager.patch`
- `disable-default-extensions.patch`
- `add-duckduckgo-search-engine.patch` (isn't a killer because you can manually do it on desktop, building swe_browser for droid specifically for this)
- `chromium-sandbox-pie.patch`

**Comment by triceratops1** [comment]
@nikolowry could you provide your pkgbuild ?

**Comment by gcarq** [comment]
Version [54.0.280.100](https://github.com/gcarq/inox-patchset/releases/tag/54.0.2840.100) is out and updated in the AUR. It took a while but finally it builds with GN build system and `safe_browsing_mode=0` :-)
