### ISSUE TITLE
Question about fieldtrial_testing_like_official_build=false

### ISSUE THREAD

**Issue by Eloston** [gcarq/inox-patchset#41]
I noticed in your [PKGBUILD file here](https://github.com/gcarq/inox-patchset/blob/master/PKGBUILD#L196) that you specified `fieldtrial_testing_like_official_build=false`.

However on line 270 of `build/config/BUILD.gn`:
```
  if (!fieldtrial_testing_like_official_build && !is_chrome_branded) {
    defines += [ "FIELDTRIAL_TESTING_ENABLED" ]
  }
```

Also notice in `build/config/features.gni`:
```
  # Set to true make a build that disables activation of field trial tests
  # specified in testing/variations/fieldtrial_testing_config_*.json.
  # Note: this setting is ignored if is_chrome_branded.
  fieldtrial_testing_like_official_build = is_chrome_branded
```

Since you're not chrome branded, does that mean you want to turn fieldtrial testing on? What's the benefit of enabling fieldtrial testing?

**Comment by gcarq** [comment]
My intention was to disable `fieldtrial_testing_like_official_build` because it's not needed in a chromium build, but as you pointed out that seems not quite true. IMO there is no reason for an open source project to force users to use fieldtrial A+B tests. Some time ago I found a [blog entry](http://www.raeknowler.name/wtf-chromium) describing up and downs of field trial tests.

**Comment by Eloston** [comment]
I've also disabled fieldtrial testing in ungoogled-chromium. It's interesting that they enable fieldtrial testing in Chromium and not Chrome.
