### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#46]
You could add thes flag (recomenden for users with ancient hardware)
https://wiki.installgentoo.com/index.php/Chromium#Reducing_RAM_Usage   

AND optionally  recomend firejail at readme.md  

you only need install firejail, and run firejail inox --options-that-you-like

https://github.com/netblue30/firejail/blob/master/etc/inox.profile

**Comment by triceratops1** [comment]
you could add a recomended extensions ad readdme?

safescript
umatrix
ublock
and https everywhere

**Comment by DragoonAethis** [comment]
@triceratops1 Most of these extensions need to be configured first to properly protect anyone. Preinstalling them gives a false sense of privacy and security. Also, not all users want to use these addons (eg they'd use Inox becuase of the Google services being disabled, but without ad blocking because that takes away money from websites).
