### ISSUE TITLE
nhacement: Add an incognio button

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#47]
COuld yoou add an incognito button

simmlilar to firefox
http://i.cubeupload.com/s5EkvW.png

**Comment by triceratops1** [comment]
pd i know the --incognito flag

but that would be NICE

**Comment by gcarq** [comment]
I don't know exactly what do you mean.
Chromium already has a button to open a new incognito tab.

**Comment by Eloston** [comment]
If you want tracking protection, go get something like uBlock Origin. If you don't want to remember history, just change content settings.

I also am not sure what you are asking for. Are you saying you want an option to launch the browser in incognito mode by default?

**Comment by triceratops1** [comment]
@gcarq 

@eloston YES

this firefox option lets you launch firefox in incognito mode by default

inox has this flag, but the --incognito flag by default would be nice

**Comment by Eloston** [comment]
Where do you want this option to be available? In `chrome://settings` or `chrome://flags`?

In terms of implementation, I think it's possible to reuse the code for setting `chrome://flags` since they are essentially command-line arguments. There may be another way to manipulate all command-line arguments though.

**Comment by gcarq** [comment]
@triceratops1 I see no benefit with enabling incognito mode by default, because Inox already blocks 3rd party cookies. Also incognito modes does not save a local browsing history and many plugins won't work by default.

You can already start it with `--incognito` and I don't think the majority of users would be happy with this change.

I want to keep the patches as small as possible and only patch unwanted tracking features, security nightmares and automated google requests.

**Comment by triceratops1** [comment]
@eloston at settings

**Comment by gcarq** [comment]
I'm closing this issue
