### ISSUE TITLE
Personal question

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#78]
What wallet do you use for ethereum?

i cant find an opensource wallet for ethereum that doesnt need to download the blockchain    (i want something like electrum)

**Comment by nyancat18** [comment]
sorry for use this space




but you accept eth donnations

and for it i ask

**Comment by gcarq** [comment]
No problem. Unfortunately there is no opensource light client for ethereum yet (AFAIK). I'm currently using parity because I prefer its web interface over mist. The parity team is working on a light client but it is still WIP: https://github.com/paritytech/parity/wiki/Light-Client. So I think we have to wait a little bit, but for now you can keep the blockchain size to a minimum with e.g. `parity --warp --no-ancient-blocks`. I'm sure there exists an equivalent option for geth, if preferred.
