### ISSUE TITLE
Binary releases and chromium 47

### ISSUE THREAD

**Issue by SethDusek** [gcarq/inox-patchset#8]
Does this support chromium 47? Also can you add .deb files and .rpm for other distros to your releases? Github allows you to create binary releases http://github.com/gcarq/inox-patchset/releases

**Comment by gcarq** [comment]
Yes the latest tested version is chromium 47.0.2526.80, but I will update it to 47.0.2526.106 the coming days. The binary releases are currently hosted at [bintray](https://bintray.com/gcarq/generic/Inox/view). I think for the next version I will switch over to Github releases.

I don't know if I'm going to release deb or rpm packages due to time limits, but until then check out [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium), he offers debian build-scripts and binaries for chromium with various patchsets.

**Comment by gcarq** [comment]
No longer relevant since version 48 is out. I added a pre-built binary (pacman pkg)
